const mongoose = require("mongoose");

const emailLogSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: [
        "general",
        "donation_appreciation",
        "donation_admin_notification",
        "subscription_confirmation",
        "subscription_admin_notification",
        "ticket",
        "welcome",
        "otp",
        "password_reset",
        "contact",
        'refund',
        "payout_account_connected",
        "payout_account_updated",
        "payout_account_disconnected",
        "withdrawal_processing",
        'withdrawal_requested',
        'withdrawal_completed',
        'withdrawal_failed',
        'team_invitation',
        'team_invitation_accepted',
        'team_invitation_declined',
        'team_member_removed',
        'team_role_updated',
        'livestream_started',
        'livestream_ended',
        'event_approved',
        'event_rejected',
        'event_canceled',
        'event_rescheduled',
        'event_update',
        'event_ended',
        'event_suspended',
        'event_unsuspended',
        'event_review_requested',
        'event_went_live',
        'subscription_renewal',
        'subscription_cancellation',
        'subscription_expired',
        'password_changed',
        'verification_successful',
        'verification_failed',
        'verification_resubmission_requested',
        'verification_suspended',
        'verification_status_updated',
        'organizer_verification_approved',
        'organizer_verification_rejected',
        'organizer_verification_request', 
        'organizer_verification_resubmission_requested',
        'organizer_verification_suspended',
        'organizer_verification_status_updated',
        'livestream_stopped',
      ],
      default: "general",
    },
    recipient: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
    },
    subject: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: ["pending", "sent", "failed"],
      default: "pending",
    },
    provider: {
      type: String,
      default: "resend",
    },
    providerId: String,
    error: String,
    attempts: {
      type: Number,
      default: 0,
    },
    lastAttemptAt: Date,
    relatedType: String,
    relatedId: mongoose.Schema.Types.Mixed,
    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("EmailLog", emailLogSchema);
